### ISSUE TITLE
[bambi benchmarks] Amelia crashes R session

### ISSUE THREAD

**Issue by okcze** [ModelOriented/EMMA#108]
Script: [link_script](https://github.com/ModelOriented/EMMA/blob/master/benchmarks/script.R)
Task ID: 50
Pipeline: PipeOpAmelia
Amelia terminates R session. Message:

> error: chol(): decomposition failed
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  chol(): decomposition failed
> Aborted (core dumped)
>

**Comment by jjanborowka** [comment]
Caller in mlr3 can help.
