### ISSUE TITLE
Experiment arrangements

### ISSUE THREAD

**Issue by woznicak** [ModelOriented/EMMA#2]
update 23.07.2020:
1. database of datasets:
- basic statistics of datasets with missing data
- searching for patterns in observations with missing values in real incomplete data and according to these
- according to founded patterns, generation missing entries in real complete data 

2. pipeline to support imputation methods:
- R package
- for multiple imputation as a default we preserve the first imputed dataset, optionally we can use multiple version of imputed data
- implementing out of range imputation
- implementing  mask with dummy encoding whether is a a missing entry

**Comment by okcze** [comment]
update 30.07.2020:
Questions for missings analysis:
- relationship of the number of patterns and the number of instances
- adding to missings distribution plot: number of columns with missings and distribution of columns types
- distribution of missings patterns on the types of variables
