### ISSUE TITLE
Comments after testing

### ISSUE THREAD

**Issue by okcze** [ModelOriented/EMMA#32]
### Information
* I am conducting the first tests taking single imputation pipe and building simple learning graph
on 3 datasets with missings using factor encoding and glmnet. I save logs to separate files (EMMA_package/tests/logs), 
where full messages are written.
* Below I will leave my comments about documentation and usage.
* As passed datasets I understand the situation when the learner was trained and scored 
(despite possible warnings during imputation)
### General remarks
- I suggest adding a link to the documentation of imputation functions from their packages to each of Pipe wrappers.
- Generally, Pipes produce a lot of output, warnings etc., from their native functions. For further development might be worth
to consider hiding all of these native prints and replace it with own messages (for example: used method, successful or not, optimized or not, with verbose option to show or hide these output).
- Parameters descriptions will be easier to understand if divided to sections (or anyway different distinguished) of parameters
passed directly to native imputation functions, and these which are additional and created in EMMA for pipe control (optimize, out_file etc.)   
- *to do after testing is complete*

### Detailed comments 
- [x] Amelia:
   - passed df: PipeImput - 1/3, PipeProc - 2/3 
   - probably more explanation for plytime /and splinetime params is needed or if they are irrelevant, maybe link to
Amelia docs, anyway I couldn't figure out what they do from docs
   - in *intercs* param description there is mentioned *optimize* param which is not described, then some *methods_random* section which I don't know where to find
   - from our meetings, I remember that *empir* param is crucial, so maybe more description about it
   - misspellings in *col_0_1* param
- [x] VIM_IRMI:
   - passed df: PipeImput - 2/3, PipeProc - 2/3
   - misspellings in *col_0_1*, *force*, *step* 
- [x] missForest:
   - passed df: PipeImput - 1/3, PipeProc - 1/3
   - *cores* param has two different default values described
   - I guess that *ntree_set* and *mtry_set* are sets of values for these params optimization when *optimize=TRUE*. 
If so, I suggest describing that or describing that they are something different if I guessed wrong.
- [x] missMDA_PCA:
   - passed df: PipeImput - 1/2, PipeProc - 1/2
   - unclear for me are *coeff.ridge* and *method* because of the same description and not listed possible values
- [x] Mice:
   - passed df: PipeImput - 3/3, PipeProc - 3/3
   - *low_corr* and *up_core* are unclear for me if they work only when *optimize* or have a different impact
   - maybe add to *set_corr* that works also only when *correlation=TRUE* (as I guess, also I know that this is the default setup but I think it's worth mentioning)
- [x] Softimpute:
   - passed df: PipeImput - 2/3, PipeProc - 2/3
   - is *lambda* default set to 0? Just seems weird from the description
   - in *type*  maybe more information about algorithms or link to softImpute docs
   - *catFun* similar as above, maybe set of more possible values or link
- [x] VIM_HD:
   - passed df: PipeImput - 3/3, PipeProc - 3/3
- [x] VIM_kNN:
   - passed df: PipeImput - 3/3, PipeProc - 3/3
   - similar for *catFUN* and *numFUN*, if some other options despite default are possible I would add more description
- [x] VIM_regrImp:
   - passed df: PipeImput - 0/3, PipeProc - 0/3
- [x] missMDA_MFA:
   - passed df: PipeImput - 0/2, PipeProc - 1/3
   - *method* might have a longer description or link
- [x] missRanger:
   - passed df: PipeImput - 3/3, PipeProc - 3/3

**Comment by jjanborowka** [comment]
Still working on problems with dataset 3719.

**Comment by jjanborowka** [comment]
All checked errors and documentation problems fixed.

**Comment by okcze** [comment]
Improvements after fixes and remake of the test.
PipeImput:
- Amelia: 2/3 
- missForest 2/3
- VIM_regrImp 2/3
- missMDA ? (not yet computed)

PipePreproc:
- missForest 2/3
- softImpute 3/3
- VIM_regrImp 2/3
- missMDA_MFA 0/3: probably in every task left missing values, errors weren't thrown, NA values in the prediction
- missMDA_MCA_PCA_FMAD 1/2: task 3793 probably left with missings, task 3667 for this test purpose is too long computed

**Comment by jjanborowka** [comment]
Problems with MFA PCA solve.
