### ISSUE TITLE
[test no. 2] VIM_HD (PipeOpTaskPreproc)

### ISSUE THREAD

**Issue by okcze** [ModelOriented/EMMA#63]
* test R script: [script](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/test_script.R)
* log: [VIM_HD log](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/logs_pipe_preproc/imput_VIM_HD.txt)
* successful usage: 9/10 tasks

> INFO  [22:12:57.002] Applying learner 'imput_VIM_HD.encodeimpact.classif.glmnet' on task 'Task 3722: hungarian (Supervised Classification)' (iter 1/5) 
> INFO  [22:12:57.537] Applying learner 'imput_VIM_HD.encodeimpact.classif.glmnet' on task 'Task 3722: hungarian (Supervised Classification)' (iter 2/5) 
> INFO  [22:12:58.449] Applying learner 'imput_VIM_HD.encodeimpact.classif.glmnet' on task 'Task 3722: hungarian (Supervised Classification)' (iter 3/5) 
> INFO  [22:12:58.997] Applying learner 'imput_VIM_HD.encodeimpact.classif.glmnet' on task 'Task 3722: hungarian (Supervised Classification)' (iter 4/5) 
> INFO  [22:12:59.469] Applying learner 'imput_VIM_HD.encodeimpact.classif.glmnet' on task 'Task 3722: hungarian (Supervised Classification)' (iter 5/5) 
> 
> 
> <ResampleResult> of 5 iterations
> * Task: Task 3722: hungarian (Supervised Classification)
> * Learner: imput_VIM_HD.encodeimpact.classif.glmnet
> * Warnings: 0 in 0 iterations
> * Errors: 0 in 0 iterations
> PROBABLY LEFT MISSINGS AFTER IMPUTATION!
> 

* Comment:
   - model prediction contained NA values, which usually occurs when missing values are present in a data frame (so probably were not imputed in our case)

**Comment by jjanborowka** [comment]
Can't be reproduced.

**Comment by okcze** [comment]
Also cannot reproduce, closing issue.
