### ISSUE TITLE
[test no. 2] VIM_KNN (PipeOpTaskPreproc)

### ISSUE THREAD

**Issue by okcze** [ModelOriented/EMMA#64]
* test R script: [script](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/test_script.R)
* log: [VIM_KNN log](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/logs_pipe_preproc/imput_VIM_kNN.txt)
* successful usage: 9/10 tasks

> INFO  [22:13:38.048] Applying learner 'imput_VIM_kNN.encodeimpact.classif.glmnet' on task 'Task 3722: hungarian (Supervised Classification)' (iter 3/5) 
> [1] 5
> [1] 5
> Ostrzeżenie w poleceniu 'VIM::kNN(df, k = k, numFun = numFun, catFun = catFun, imp_var = F)':
>   All observations of feature are missing, therefore the variable will not be imputed!
> 
> Ostrzeżenie w poleceniu 'FUN(newX[, i], ...)':
>   brak argumentów w min; zwracanie wartości Inf
> Ostrzeżenie w poleceniu 'FUN(newX[, i], ...)':
>   brak argumentów w max; zwracanie wartości -Inf
> Ostrzeżenie w poleceniu 'FUN(newX[, i], ...)':
>   brak argumentów w min; zwracanie wartości Inf
> Ostrzeżenie w poleceniu 'FUN(newX[, i], ...)':
>   brak argumentów w max; zwracanie wartości -Inf
> Ostrzeżenie w poleceniu 'FUN(newX[, i], ...)':
>   brak argumentów w min; zwracanie wartości Inf
> Ostrzeżenie w poleceniu 'FUN(newX[, i], ...)':
>   brak argumentów w max; zwracanie wartości -Inf
> Error in indexNA2s[, variable[j]] : indeks jest poza granicami
>

**Comment by jjanborowka** [comment]
Imputation doesn't work if the feature contains only NA. Better error description added.
