### ISSUE TITLE
[test no. 2] VIM_regrImp (PipeOpTaskPreproc)

### ISSUE THREAD

**Issue by okcze** [ModelOriented/EMMA#65]
* test R script: [script](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/test_script.R)
* log: [VIM_regrImp log](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/logs_pipe_preproc/imput_VIM_regrImp.txt)
* successful usage: 4/10 tasks

> INFO  [22:14:35.457] Applying learner 'imput_VIM_regrImp.encodeimpact.classif.glmnet' on task 'Task 3543: irish (Supervised Classification)' (iter 4/5) 
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])':
>   group ‘Senior_cycle_incomplete-secondary_school’ is empty
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])':
>   group ‘Senior_cycle_incomplete-secondary_school’ is empty
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])':
>   group ‘Senior_cycle_incomplete-secondary_school’ is empty
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])':
>   group ‘Senior_cycle_incomplete-secondary_school’ is empty
> character(0)
> [1] "Error in doTryCatch(return(expr), name, parentenv, handler): \n"
> Error in try({ : 
>

**Comment by okcze** [comment]
> INFO  [22:14:37.005] Applying learner 'imput_VIM_regrImp.encodeimpact.classif.glmnet' on task 'Task 3722: hungarian (Supervised Classification)' (iter 1/5) 
> Ostrzeżenie w poleceniu 'predict.lm(mod, newdata = tmp)':
>   prediction from a rank-deficient fit may be misleading
> Ostrzeżenie w poleceniu 'predict.lm(mod, newdata = tmp)':
>   prediction from a rank-deficient fit may be misleading
> character(0)
> [1] "Error in doTryCatch(return(expr), name, parentenv, handler): \n"
> Error in try({ : 
>

**Comment by okcze** [comment]
> INFO  [22:14:38.735] Applying learner 'imput_VIM_regrImp.encodeimpact.classif.glmnet' on task 'Task 29: credit-approval (Supervised Classification)' (iter 1/5) 
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])': group ‘t’ is empty
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])': groups ‘l’ ‘t’ are empty
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])': groups ‘l’ ‘t’ are empty
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])': groups ‘l’ ‘t’ are empty
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])': groups ‘l’ ‘t’ are empty
> character(0)
> [1] "Error in doTryCatch(return(expr), name, parentenv, handler): \n"
> Error in try({ : 
>

**Comment by okcze** [comment]
> INFO  [22:14:44.623] Applying learner 'imput_VIM_regrImp.encodeimpact.classif.glmnet' on task 'Task 14954: cylinder-bands (Supervised Classification)' (iter 1/5) 
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])':
>   groups ‘84’ ‘uddeholm’ are empty
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])':
>   groups ‘84’ ‘uddeholm’ are empty
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])':
>   groups ‘84’ ‘uddeholm’ are empty
> Ostrzeżenie w poleceniu 'multinom(form, data[TFna, ])':
>   groups ‘84’ ‘uddeholm’ are empty
> character(0)
> [1] "Error in doTryCatch(return(expr), name, parentenv, handler): \n"
> Error in try({ : 
>

**Comment by okcze** [comment]
> INFO  [22:14:46.356] Applying learner 'imput_VIM_regrImp.encodeimpact.classif.glmnet' on task 'Task 48: heart-c (Supervised Classification)' (iter 2/5) 
> character(0)
> [1] "Error in doTryCatch(return(expr), name, parentenv, handler): \n"
> Error in try({ : 
>

**Comment by okcze** [comment]
> INFO  [22:14:47.942] Applying learner 'imput_VIM_regrImp.encodeimpact.classif.glmnet' on task 'Task 3561: profb (Supervised Classification)' (iter 1/5) 
> character(0)
> [1] "Error in doTryCatch(return(expr), name, parentenv, handler): \n"
> Error in try({ : 
>

**Comment by jjanborowka** [comment]
Constant columns.
