### ISSUE TITLE
[test no. 2] missRanger (PipeOpTaskPreproc)

### ISSUE THREAD

**Issue by okcze** [ModelOriented/EMMA#66]
* test R script: [script](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/test_script.R)
* log: [missRanger log](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/logs_pipe_preproc/imput_missRanger.txt)
* successful usage: 9/10 tasks

> INFO  [22:15:13.400] Applying learner 'imput_missRanger.encodeimpact.classif.glmnet' on task 'Task 3722: hungarian (Supervised Classification)' (iter 3/5) 
> Ostrzeżenie: Dropped unused factor level(s) in dependent variable: 3.
> Error in pmm(xtrain = fit$predictions, xtest = pred, ytrain = data[[v]][!v.na],  : 
>   zmienna sum(ok <- !is.na(xtrain) & !is.na(ytrain)) >= 1L nie ma wartości TRUE
>

**Comment by jjanborowka** [comment]
Imputation doesn't work if feature contain only NA.
