### ISSUE TITLE
[test no. 2] softImpute (PipeImpute)

### ISSUE THREAD

**Issue by okcze** [ModelOriented/EMMA#84]
* test R script: [script](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/test_script.R)
* log: [softImpute log](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/logs/imput_softImpute.txt)
* successful usage: 3/10 tasks

> INFO  [22:12:33.475] Applying learner 'imput_softImpute.encodeimpact.classif.glmnet' on task 'Task 3722: hungarian (Supervised Classification)' (iter 1/5) 
> Ostrzeżenie w poleceniu '`[<-.factor`(`*tmp*`, is.na(col_to_imp), value = "NA's")':
>   niepoprawny poziom czynnika, wygenerowano wartość NA
> Ostrzeżenie w poleceniu '`[<-.factor`(`*tmp*`, is.na(col_to_imp), value = "NA's")':
>   niepoprawny poziom czynnika, wygenerowano wartość NA
> Error in lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs,  : 
>   wartość NA/NaN/Inf w wywołaniu obcej funcji (argument 5)
> 
Probably this error is thrown by glmnet when missing values were present in data.

**Comment by okcze** [comment]
> INFO  [22:12:45.804] Applying learner 'imput_softImpute.encodeimpact.classif.glmnet' on task 'Task 3561: profb (Supervised Classification)' (iter 1/5) 
> Ostrzeżenie w poleceniu '`[<-.factor`(`*tmp*`, is.na(col_to_imp), value = "NA's")':
>   niepoprawny poziom czynnika, wygenerowano wartość NA
> Ostrzeżenie w poleceniu '`[<-.factor`(`*tmp*`, is.na(col_to_imp), value = "NA's")':
>   niepoprawny poziom czynnika, wygenerowano wartość NA
> Error in lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs,  : 
>   wartość NA/NaN/Inf w wywołaniu obcej funcji (argument 5)
>

**Comment by okcze** [comment]
> INFO  [22:12:47.059] Applying learner 'imput_softImpute.encodeimpact.classif.glmnet' on task 'Task 3675: pbc (Supervised Classification)' (iter 1/5) 
> INFO  [22:12:47.534] Applying learner 'imput_softImpute.encodeimpact.classif.glmnet' on task 'Task 3675: pbc (Supervised Classification)' (iter 2/5) 
> INFO  [22:12:48.043] Applying learner 'imput_softImpute.encodeimpact.classif.glmnet' on task 'Task 3675: pbc (Supervised Classification)' (iter 3/5) 
> Ostrzeżenie w poleceniu '`[<-.factor`(`*tmp*`, is.na(col_to_imp), value = "NA's")':
>   niepoprawny poziom czynnika, wygenerowano wartość NA
> INFO  [22:12:48.876] Applying learner 'imput_softImpute.encodeimpact.classif.glmnet' on task 'Task 3675: pbc (Supervised Classification)' (iter 4/5) 
> INFO  [22:12:49.340] Applying learner 'imput_softImpute.encodeimpact.classif.glmnet' on task 'Task 3675: pbc (Supervised Classification)' (iter 5/5) 
> 
> 
> <ResampleResult> of 5 iterations
> * Task: Task 3675: pbc (Supervised Classification)
> * Learner: imput_softImpute.encodeimpact.classif.glmnet
> * Warnings: 0 in 0 iterations
> * Errors: 0 in 0 iterations
> PROBABLY LEFT MISSINGS AFTER IMPUTATION!
>

**Comment by jjanborowka** [comment]
Already solve.
