### ISSUE TITLE
[test no. 2] VIM_HD (PipeImpute)

### ISSUE THREAD

**Issue by okcze** [ModelOriented/EMMA#86]
* test R script: [script](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/test_script.R)
* log: [VIM_HD log](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/logs/imput_VIM_HD.txt)
* successful usage: 9/10 tasks

> INFO  [22:12:59.469] Applying learner 'imput_VIM_HD.encodeimpact.classif.glmnet' on task 'Task 3722: hungarian (Supervised Classification)' (iter 5/5) 
> 
> 
> <ResampleResult> of 5 iterations
> * Task: Task 3722: hungarian (Supervised Classification)
> * Learner: imput_VIM_HD.encodeimpact.classif.glmnet
> * Warnings: 0 in 0 iterations
> * Errors: 0 in 0 iterations
> PROBABLY LEFT MISSINGS AFTER IMPUTATION!
>

**Comment by jjanborowka** [comment]
Contain vector with NA only after cv. This happens only in a fraction of cv iteration.
