### ISSUE TITLE
[test no. 2] VIM_regrImp (PipeImpute)

### ISSUE THREAD

**Issue by okcze** [ModelOriented/EMMA#90]
* test R script: [script](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/test_script.R)
* log: [VIM_regrImp log](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_2/logs/imput_VIM_regrImp.txt)
* successful usage: 4/10 tasks
The same errors as in PipePreProc version occurred [issue](https://github.com/ModelOriented/EMMA/issues/65)

**Comment by jjanborowka** [comment]
Constant columns
