### ISSUE TITLE
[test no. 3] mice (PipeImpute)

### ISSUE THREAD

**Issue by okcze** [ModelOriented/EMMA#95]
Test version without preprocessing of datasets.
Test log: [mice log](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_3_no_cleaning/logs/imput_mice.txt)

> INFO  [09:28:14.248] Applying learner 'imput_mice.encodeimpact.classif.glmnet' on task '3807' (iter 1/5) 
> Ostrzeżenie: Number of logged events: 1
> INFO  [09:28:15.452] Applying learner 'imput_mice.encodeimpact.classif.glmnet' on task '3807' (iter 2/5) 
> Ostrzeżenie: Number of logged events: 25
> INFO  [09:28:17.239] Applying learner 'imput_mice.encodeimpact.classif.glmnet' on task '3807' (iter 3/5) 
> INFO  [09:28:18.542] Applying learner 'imput_mice.encodeimpact.classif.glmnet' on task '3807' (iter 4/5) 
> Ostrzeżenie: Number of logged events: 40
> INFO  [09:28:19.834] Applying learner 'imput_mice.encodeimpact.classif.glmnet' on task '3807' (iter 5/5) 
> 
> 
> <ResampleResult> of 5 iterations
> * Task: 3807
> * Learner: imput_mice.encodeimpact.classif.glmnet
> * Warnings: 0 in 0 iterations
> * Errors: 0 in 0 iterations
> PROBABLY LEFT MISSINGS AFTER IMPUTATION!

**Comment by jjanborowka** [comment]
Same as. https://github.com/ModelOriented/EMMA/issues/57
