### ISSUE TITLE
[test no. 3] VIM_IRMI (PipePreproc)

### ISSUE THREAD

**Issue by okcze** [ModelOriented/EMMA#96]
Test version without preprocessing of datasets.
Test log: [IRMI](https://github.com/ModelOriented/EMMA/blob/master/EMMA_package/tests/round_3_no_cleaning/logs_pipe_preproc/imput_VIM_IRMI_.txt)
> INFO  [09:37:51.610] Applying learner 'imput_VIM_IRMI.encodeimpact.classif.glmnet' on task '3802' (iter 1/5) 
> [1] "IRMI dont work on selcted params runing on defoult"
> Error in colnames(final) : nie znaleziono obiektu 'final'
>

**Comment by jjanborowka** [comment]
I can't reproduce this issue but the problem is probably solved.
